# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dna_spaces_pb2 as dna__spaces__pb2


class FirehoseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEvents = channel.unary_stream(
                '/firehose_api_v1.Firehose/GetEvents',
                request_serializer=dna__spaces__pb2.EventsStreamRequest.SerializeToString,
                response_deserializer=dna__spaces__pb2.EventRecord.FromString,
                )
        self.GetLocationInfo = channel.unary_unary(
                '/firehose_api_v1.Firehose/GetLocationInfo',
                request_serializer=dna__spaces__pb2.LocationInfoRequest.SerializeToString,
                response_deserializer=dna__spaces__pb2.LocationInfo.FromString,
                )
        self.GetFloorMap = channel.unary_unary(
                '/firehose_api_v1.Firehose/GetFloorMap',
                request_serializer=dna__spaces__pb2.FloorMapRequest.SerializeToString,
                response_deserializer=dna__spaces__pb2.FloorMap.FromString,
                )
        self.SaveDevice = channel.unary_unary(
                '/firehose_api_v1.Firehose/SaveDevice',
                request_serializer=dna__spaces__pb2.SaveDeviceRequest.SerializeToString,
                response_deserializer=dna__spaces__pb2.Device.FromString,
                )
        self.GetDevice = channel.unary_unary(
                '/firehose_api_v1.Firehose/GetDevice',
                request_serializer=dna__spaces__pb2.GetDeviceRequest.SerializeToString,
                response_deserializer=dna__spaces__pb2.Device.FromString,
                )


class FirehoseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocationInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFloorMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FirehoseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.GetEvents,
                    request_deserializer=dna__spaces__pb2.EventsStreamRequest.FromString,
                    response_serializer=dna__spaces__pb2.EventRecord.SerializeToString,
            ),
            'GetLocationInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocationInfo,
                    request_deserializer=dna__spaces__pb2.LocationInfoRequest.FromString,
                    response_serializer=dna__spaces__pb2.LocationInfo.SerializeToString,
            ),
            'GetFloorMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFloorMap,
                    request_deserializer=dna__spaces__pb2.FloorMapRequest.FromString,
                    response_serializer=dna__spaces__pb2.FloorMap.SerializeToString,
            ),
            'SaveDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveDevice,
                    request_deserializer=dna__spaces__pb2.SaveDeviceRequest.FromString,
                    response_serializer=dna__spaces__pb2.Device.SerializeToString,
            ),
            'GetDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevice,
                    request_deserializer=dna__spaces__pb2.GetDeviceRequest.FromString,
                    response_serializer=dna__spaces__pb2.Device.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'firehose_api_v1.Firehose', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Firehose(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/firehose_api_v1.Firehose/GetEvents',
            dna__spaces__pb2.EventsStreamRequest.SerializeToString,
            dna__spaces__pb2.EventRecord.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLocationInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firehose_api_v1.Firehose/GetLocationInfo',
            dna__spaces__pb2.LocationInfoRequest.SerializeToString,
            dna__spaces__pb2.LocationInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFloorMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firehose_api_v1.Firehose/GetFloorMap',
            dna__spaces__pb2.FloorMapRequest.SerializeToString,
            dna__spaces__pb2.FloorMap.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firehose_api_v1.Firehose/SaveDevice',
            dna__spaces__pb2.SaveDeviceRequest.SerializeToString,
            dna__spaces__pb2.Device.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/firehose_api_v1.Firehose/GetDevice',
            dna__spaces__pb2.GetDeviceRequest.SerializeToString,
            dna__spaces__pb2.Device.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
